title: "LLMs: From Foundations to Production"
description: "A comprehensive tutorial for mastering Large Language Models (LLMs) â€“ from core mathematics and computing principles to production deployment, advanced applications, and emerging research trends."
color_scheme: light
search_enabled: true
remote_theme: tomjoht/documentation-theme-jekyll

github: "https://github.com/mshojaei77/LLMs-Journey"

# Logo
logo: "/assets/img/logo.png"

plugins:
  - jekyll-default-layout
  
favicon_ico: "/assets/img/favicon.ico"

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/mshojaei77"

aux_links_new_tab: true

